x-xia-common: &xia_common
  build: .
  cap_add:
    - NET_ADMIN
    - NET_RAW
  volumes:
    - resolv_share:/shared

services:
  router1:
    <<: *xia_common
    container_name: router1
    hostname: router1
    environment:
      ROLE: router
      NAMESERVER: "true"
      AD_NAME: "AD-1"
      IGNORE_IFACES: "lo"
      ALL_NODES: "host0 server0 server1"
    networks:
      - net_r0_r1
      - net_r1_r2

  router0:
    <<: *xia_common
    container_name: router0
    hostname: router0
    depends_on:
      - router1
    environment:
      ROLE: router
      NAMESERVER: "false"
      AD_NAME: "AD-0"
      IGNORE_IFACES: "lo"
      ALL_NODES: "host0 server0 server1"
    networks:
      - net_h0_r0
      - net_r0_r1

  router2:
    <<: *xia_common
    container_name: router2
    hostname: router2
    depends_on:
      - router1
    environment:
      ROLE: router
      NAMESERVER: "false"
      AD_NAME: "AD-2"
      IGNORE_IFACES: "lo"
      ALL_NODES: "host0 server0 server1"
    networks:
      - net_r1_r2
      - net_r2_s0
      - net_r2_s1

  host0:
    <<: *xia_common
    container_name: host0
    hostname: host0
    depends_on:
      - router0
    environment:
      ROLE: host
      AD_NAME: "HOST-0"
      IGNORE_IFACES: "lo"
      ALL_NODES: "host0 server0 server1"
    networks:
      - net_h0_r0

  server0:
    <<: *xia_common
    container_name: server0
    hostname: server0
    depends_on:
      - router2
    environment:
      ROLE: host
      AD_NAME: "SERVER-0"
      IGNORE_IFACES: "lo"
      ALL_NODES: "host0 server0 server1"
    networks:
      - net_r2_s0

  server1:
    <<: *xia_common
    container_name: server1
    hostname: server1
    depends_on:
      - router2
    environment:
      ROLE: host
      AD_NAME: "SERVER-1"
      IGNORE_IFACES: "lo"
      ALL_NODES: "host0 server0 server1"
    networks:
      - net_r2_s1

networks:
  net_h0_r0:
    internal: true
  net_r0_r1:
    internal: true
  net_r1_r2:
    internal: true
  net_r2_s0:
    internal: true
  net_r2_s1:
    internal: true

volumes:
  resolv_share:
