#!/bin/bash

# Startup script for XIA router nodes.
#
# Generalized along two axes (previously this script only supported the
# single-router-is-always-the-nameserver case):
#
#   XIA_NAMESERVER   "1" if this router should run the nameserver, "0" (or
#                    unset) if it's a plain router that must fetch resolv.conf
#                    from whichever router IS the nameserver. Exactly one
#                    router in the whole network should set this to "1".
#
#   XIA_PEER_HOSTS   Space-separated list of HOST node hostnames directly
#                    attached to THIS router's local AD (e.g. "host0" for
#                    router0, "server0 server1" for router2). Leave unset/
#                    empty for a pure transit router with no local hosts
#                    (e.g. router1 in a 3-router backbone) -- in that case
#                    the local hosts.xia build and self-route fix are
#                    skipped entirely, since there's nothing local to fix.
#


cd /opt/xia-core

rsyslogd

rm -f /tmp/xsocket* /tmp/icid* /tmp/xcache* /tmp/click*
./bin/xianet kill || true

mkdir -p /shared

# Clean up this router's OWN locally-attached host DAG files from any
# previous run. Only touch entries for hosts that are actually ours.
if [ -n "$XIA_PEER_HOSTS" ]; then
    for n in $XIA_PEER_HOSTS; do
        rm -f /shared/dag_$n.txt
    done
fi

if [ "$XIA_NAMESERVER" = "1" ]; then
    # ---- Nameserver router ----

    # Remove resolver state from a previous Docker run. The xia-shared
    # volume survives container recreation.
    rm -f /shared/resolv.conf
    rm -f /shared/nameserver.ready

    echo "[$(hostname)] starting XIA router + nameserver..."
    ./bin/xianet -r -n start || true

    # Wait for xianet to generate the CURRENT resolv.conf, then publish it
    # on the shared volume so other routers and host nodes can pick it up.
    until [ -f etc/resolv.conf ]; do
        sleep 1
    done

    cp etc/resolv.conf /shared/resolv.conf

    # Only signal readiness AFTER the complete current resolver has
    # been published.
    touch /shared/nameserver.ready

    echo "[$(hostname)] published current resolv.conf:"
    cat /shared/resolv.conf

    # This router's own HID is safely readable from etc/resolv.conf here,
    # since it was generated by this node's own xianet -r -n start.
    # router_hid=$(awk '{ for (i = 1; i <= NF; i++) if ($i ~ /^HID:/) { print $i; exit } }' etc/resolv.conf)
    




else
    # ---- Plain (non-nameserver) router ----

    echo "[$(hostname)] starting XIA router..."
    echo "[$(hostname)] waiting for nameserver router..."

    until [ -f /shared/nameserver.ready ]; do
        sleep 1
    done

    cp /shared/resolv.conf etc/resolv.conf

    echo "[$(hostname)] using nameserver:"
    cat etc/resolv.conf

    ./bin/xianet -r start || true

    echo "[$(hostname)] own router HID: $router_hid"


    fi

router_hid=$(awk '{ for (i = 1; i <= NF; i++) if ($i ~ /^HID:/) { sub(/\)$/, "", $i); print $i; exit } }' etc/address.conf)

if [ -z "$router_hid" ]; then
    echo "[$(hostname)] unable to determine this router's own HID" >&2
    exit 1
fi

echo "[$(hostname)] own router HID: $router_hid"

# ----------------------------------------------------------------------
# Restore this router's own HID as a LOCAL route.
#
# This must happen even for a transit/nameserver router with no local
# hosts. The nameserver itself needs a valid local route to its own HID
# when processing XIA name-resolution traffic.
# ----------------------------------------------------------------------

./bin/xroute -a "HID,${router_hid},-2"
echo "[$(hostname)] restored router self-route for $router_hid"

if [ -n "$XIA_PEER_HOSTS" ]; then
    # --------------------------------------------------------------
    # This router has locally attached hosts.
    # --------------------------------------------------------------

    echo "[$(hostname)] waiting for local peer hosts: $XIA_PEER_HOSTS"

    for n in $XIA_PEER_HOSTS; do
        until [ -s "/shared/dag_$n.txt" ]; do
            sleep 1
        done
    done

    echo "[$(hostname)] all local peer hosts are ready"

    # Bundle the currently published host DAGs.
    cat /shared/dag_*.txt > etc/hosts.xia

    echo "[$(hostname)] hosts.xia ready:"
    cat etc/hosts.xia

    # Host network joining can replace the router's local HID route
    # with a route through port 0 whose next hop is the router itself.
    # Restore the local route after all local hosts have joined.
    ./bin/xroute -a "HID,${router_hid},-2"

    echo "[$(hostname)] restored router self-route for $router_hid after host joins"

else
    echo "[$(hostname)] no local peer hosts configured (transit router) -- skipping hosts.xia"
fi

./bin/xianet check || true

tail -f /dev/null
